travis:
  secure:
    BINSTAR_TOKEN: sAVoTJbt1sOuiyaO09/61hhTjcPgkX/l9Ok/2VCWoNrIEz0tczlgV9W/Zt/hyvJUKp2dIHeQ8ViGnRZVZyn9rAysLfUlVd10MmSqf4Y8E6kWhi4vO7AGxRH6sRQAwZ2gmtJufuMOGY1NhWZFnfibQWtBYX+EySQDzA9DJSn8QR6OYx0v0IEykRxWBXFxnr9MCxO7FH8CQjWzf7OjUz/TfF+Y3SUsDnaJDSuY49J8Xlw2ixQFxJnCRCIOAXkUIba/EAiw2IFXs9pVjbQTXrCrgUs+5DgLMtuwjfQCxLLqCkChnGaXkYt2XcOBYSt97faVBI22EmT/YFlwNd/0KMdBC0YrWZbXYo5CvNdGRFLrufXKJYT14WeMd2gIkoL73vQX+ET03gDkKjhxHSZYx+dLH8sbZmJbQxeOjmEDeNxjO5sRJSQT4aT1hCDAlR8nQsK4ZDIAyUvG6YXZgcOzUahHhi5snsWPRZkM3z9sKSQ2FwPHNKaKgEmyJzAlwLgxCNIwM1tv25xw8K5RJUI2mXYbswH/K/FsoevS0P+Qwq9npGdLIHoxzz19FULCVUMwUMj/3sVjBCZrBvDTuxx20i9KXhhHnQ8yVI9GQ6mKCG9YIYNup6pPtXFghWV58PXqozgRE0k/VgSlTx9shvuMAOHIHySYcr8lyOEpQgw7zdA1ZBQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
